[package]
name = "pxm-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-util = "0.7"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "json", "chrono"] }
uuid = { version = "1", features = ["v4", "serde"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
anyhow = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
mongodb = { version = "2.8.2", default-features = false, features = ["tokio-runtime"] }
futures-util = "0.3"
