services:
  db:
    image: postgres:16
    container_name: pxm-db
    environment:
      POSTGRES_USER: pxm
      POSTGRES_PASSWORD: bpm
      POSTGRES_DB: pxm
    ports:
      - "5432:5432"
    volumes:
      - pxm_pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro

  mongodb:
    image: mongo:7.0
    container_name: pxm-mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - pxm_mongodata:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"try { rs.status().ok } catch (e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}).ok }\" | grep 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pxm_pgdata:
  pxm_mongodata:
