/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 가능한 워크플로우 목록 조회 */
        get: operations["Templates_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크플로우 상세 조회 */
        get: operations["Templates_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 워크플로우 실행
         * @description API Key 요청은 배포된 버전만 실행합니다.
         */
        post: operations["Templates_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 워크플로우 실행 (호환 별칭) */
        post: operations["Templates_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 접근 가능한 실행 목록 조회 */
        get: operations["Instances_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 상태 조회 */
        get: operations["Instances_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 결과 조회 */
        get: operations["Instances_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실행 종료
         * @description workflow:execute scope와 대상 워크플로우 권한이 필요하며, 같은 소유자의 API Key로 시작한 실행만 종료할 수 있습니다. Key를 재발급해도 소유자가 같으면 종료할 수 있습니다. 이미 최종 상태인 실행은 성공 응답과 빈 terminated_instances를 반환합니다.
         */
        post: operations["Instances_terminate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 Trace 조회 */
        get: operations["Instances_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 이벤트 스트림 구독 */
        get: operations["Instances_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 결재 대기 목록 조회 */
        get: operations["Tasks_getTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 이력 조회 */
        get: operations["Tasks_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 상세 조회 */
        get: operations["Tasks_historyItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결재 승인 또는 반려 */
        post: operations["Tasks_completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instanceId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 인스턴스의 결재 이력 조회 */
        get: operations["InstanceTasks_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool 목록
         * @description tool:read 권한 범위가 필요합니다. 응답은 LLM tool 정의로 바로 바꿀 수 있는 모양입니다. naming=auto(기본)는 이름이 겹치는 Tool만 한정 이름을 씁니다. 여러 턴에 걸쳐 이름을 캐시하면 naming=qualified를 쓰세요.
         */
        get: operations["Tools_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/invocations/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool 호출 결과 확인
         * @description tool:invoke 권한 범위가 필요합니다. 202(pending_approval·running)를 받은 뒤 이 주소로 결과를 확인합니다. 응답 모양은 실행 API와 같습니다.
         */
        get: operations["Tools_invocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool 상세
         * @description tool:read 권한 범위가 필요합니다. 이름은 Tool 이름 또는 한정 이름입니다.
         */
        get: operations["Tools_describe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{name}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tool 실행
         * @description tool:invoke 권한 범위가 필요합니다. Tool에 고정된 워크플로우 버전을 실행합니다. 200 ok(완료) / 200 error(업무 실패, 재시도하지 않음) / 202 pending_approval(결재 대기) / 202 running(진행 중). 실행 실패는 원인별 HTTP 코드와 failure_type·retryable을 줍니다. 자동 재시도는 HTTP 코드가 아니라 retryable로 판단하고, side_effect가 read_only가 아니면 첫 호출과 같은 Idempotency-Key로 재시도하세요.
         */
        post: operations["Tools_invoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    workflowResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PXM이 외부 시스템으로 전송하는 최종 결재 결과
         * @description 서명 입력은 `${X-PXM-Timestamp}.${raw_request_body}`이며 HMAC-SHA256으로 검증합니다. 동일 Idempotency-Key는 중복 처리하지 않습니다.
         *
         *     ```js
         *     const expected = 'v1=' + createHmac('sha256', secret)
         *       .update(`${timestamp}.${rawBody}`)
         *       .digest('hex');
         *     const valid = timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
         *     ```
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-PXM-Event-Id": string;
                    "X-PXM-Timestamp": string;
                    "X-PXM-Signature": string;
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowResultWebhookDto"];
                };
            };
            responses: {
                /** @description 처리 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 이미 처리한 이벤트 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        PublicApiErrorDto: {
            /** @example 403 */
            statusCode: number;
            /** @example Forbidden */
            error: string;
            /** @example MISSING_SCOPE */
            code: string;
            /** @example workflow:execute scope is required */
            message: string;
            details?: string[];
            /** @example workflow:execute */
            required_scope?: string;
            /** @example client-request-42 */
            request_id: string;
            /** Format: date-time */
            timestamp: string;
            /** @example /api/v1/templates/workflow-1/start */
            path: string;
        };
        WorkflowDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            group?: string;
            group_id?: Record<string, never> | null;
            tags: string[];
            version: number;
            /** @enum {string} */
            lifecycle_status: "DRAFT" | "PUBLISHED" | "DISABLED";
            nodes: {
                [key: string]: unknown;
            }[];
            edges: {
                [key: string]: unknown;
            }[];
        };
        StartWorkflowDto: {
            /**
             * @default async
             * @enum {string}
             */
            mode: "async" | "sync";
            sync_timeout_ms?: number;
            input?: {
                [key: string]: unknown;
            };
            /**
             * @example {
             *       "requestTitle": "구매 승인",
             *       "amount": 125000
             *     }
             */
            formData?: {
                [key: string]: unknown;
            };
            preset?: string;
            preset_id?: string;
            preset_alias?: string;
        };
        StartWorkflowResponseDto: {
            /** Format: uuid */
            instance_id: string;
            /** Format: uuid */
            template_id: string;
            template_name: string;
            /** @example CREATED */
            status: string;
            /** @enum {string} */
            mode: "async" | "sync";
            idempotent_replay: boolean;
            /** @example /api/v1/instances/instance-id/result */
            result_url: string;
            /** @example /api/v1/instances/instance-id/trace */
            trace_url: string;
            /** @example /api/v1/instances/instance-id/stream */
            stream_url: string;
        };
        InstanceDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            process_definition_id?: string;
            /** @example RUNNING */
            state: string;
            context?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        InstanceOutcomeReasonDto: {
            /**
             * @description 프로그램에서 분기할 안정적인 결과 코드
             * @example APPROVAL_REJECTED
             */
            code: string;
            /**
             * @description FAILURE의 원인 분류: configuration | upstream_error | timeout | script_error | subworkflow_failed | internal. 업무 결과(반려 등)는 business
             * @example upstream_error
             */
            failure_type?: Record<string, never> | null;
            /** @description 같은 입력으로 다시 실행하면 성공할 수 있는지. 자동 재시도 판단은 이 값을 기준으로 한다 */
            retryable?: boolean;
            message?: Record<string, never> | null;
            node_id?: Record<string, never> | null;
        };
        InstanceResultDto: {
            /** Format: uuid */
            instance_id: string;
            /**
             * @description 실행 상태. 업무 결과는 outcome을 본다
             * @example COMPLETED
             */
            status: string;
            /**
             * @description 업무 결과. 종료 전에는 null. 결재 반려는 status가 COMPLETED여도 REJECTED다
             * @enum {string|null}
             */
            outcome?: "SUCCESS" | "REJECTED" | "FAILURE" | "CANCELLED" | null;
            outcome_reason?: components["schemas"]["InstanceOutcomeReasonDto"] | null;
            result?: {
                [key: string]: unknown;
            } | null;
            result_path?: Record<string, never> | null;
            /** Format: date-time */
            completed_at?: Record<string, never> | null;
            /** Format: date-time */
            updated_at?: Record<string, never> | null;
        };
        TerminateInstanceResponseDto: {
            /** @example true */
            success: boolean;
            /** Format: uuid */
            instance_id: string;
            /** @description 이번 요청에서 종료 상태로 바뀐 실행 ID. 이미 종료된 실행이면 빈 배열입니다. */
            terminated_instances: string[];
            /** @example false */
            idempotent_replay: boolean;
        };
        TraceEventDto: {
            id: number;
            event_type?: string;
            node_id?: string;
            node_label?: string;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        ApprovalHoldDto: {
            actor_id: string;
            comment?: Record<string, never> | null;
            /** Format: date-time */
            held_at: string;
        };
        ApprovalTaskDto: {
            task_id: string;
            instance_id: string;
            workflow_id?: Record<string, never> | null;
            workflow_name?: Record<string, never> | null;
            node_label?: Record<string, never> | null;
            /** @example OPEN */
            status: string;
            assignee: string;
            /** @example pxm_user */
            approver_channel: string;
            approval_channels?: string[];
            action?: Record<string, never> | null;
            comment?: Record<string, never> | null;
            hold?: components["schemas"]["ApprovalHoldDto"] | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: Record<string, never> | null;
        };
        ApprovalTaskPageDto: {
            items: components["schemas"]["ApprovalTaskDto"][];
            next_cursor?: Record<string, never> | null;
        };
        CompleteApprovalDto: {
            /** @enum {string} */
            action: "approve" | "reject";
            comment?: string;
            result?: {
                [key: string]: unknown;
            };
        };
        ToolDefinitionDto: {
            /**
             * @description LLM에 넣을 이름. naming에 따라 tool_name 또는 qualified_name
             * @example request_access
             */
            name: string;
            /** @example request_access */
            tool_name: string;
            /**
             * @description {그룹 공개 이름}__{Tool 이름}. Tool 수명 동안 바뀌지 않는다
             * @example security-ops__request_access
             */
            qualified_name: string;
            display_name?: Record<string, never> | null;
            /** @description LLM이 Tool을 고를 때 읽는 설명 */
            description: string;
            /** @description JSON Schema */
            input_schema: {
                [key: string]: unknown;
            };
            output_schema?: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            output_contract: "declared" | "free_form";
            /** @enum {string} */
            side_effect: "read_only" | "mutating" | "requires_approval";
            tags: string[];
            group_id: string;
            group_name?: Record<string, never> | null;
            namespace?: Record<string, never> | null;
            /** @description 쓸 수 있는 Tool 중 같은 tool_name이 다른 그룹에도 있음 */
            name_conflict: boolean;
            pinned_version: number;
        };
        ToolListResponseDto: {
            tools: components["schemas"]["ToolDefinitionDto"][];
            has_name_conflict: boolean;
        };
        ToolInvokeErrorDto: {
            /** @enum {string} */
            kind: "business";
            /** @example APPROVAL_REJECTED */
            code: string;
            message: string;
            /** @example false */
            retryable: boolean;
        };
        ToolInvokeResponseDto: {
            tool: string;
            qualified_name: string;
            /** @enum {string} */
            status: "ok" | "error" | "pending_approval" | "running";
            /** Format: uuid */
            instance_id: string;
            /** @enum {string|null} */
            outcome?: "SUCCESS" | "REJECTED" | "FAILURE" | null;
            /** @description 업무 결과 (End 노드 결과) */
            result?: Record<string, never> | null;
            /** @description status=error일 때 업무 실패 내용. 재시도 대상이 아니다 */
            error?: components["schemas"]["ToolInvokeErrorDto"];
            /** @description status=pending_approval일 때 결재 대기 정보 */
            pending?: {
                [key: string]: unknown;
            };
            result_url: string;
            /** @description workflow:read가 있을 때만 준다 */
            trace_url?: string;
            /** @description workflow:read가 있을 때만 준다 */
            stream_url?: string;
            idempotent_replay: boolean;
            request_id: string;
        };
        ToolInvokeDto: {
            /** @description input_schema를 따르는 인자 */
            arguments?: {
                [key: string]: unknown;
            };
            /** @description 일반 이름이 여러 그룹에 있을 때 그룹을 정한다 */
            group_id?: string;
            /**
             * @default sync
             * @enum {string}
             */
            mode: "sync" | "async";
            sync_timeout_ms?: number;
        };
        WorkflowResultWebhookSourceDto: {
            /** @example acrapoint */
            provider: string;
            /** @example ACRA-2026-0042 */
            request_id: string;
            /** @example 1 */
            revision: number;
        };
        WorkflowResultWebhookDataDto: {
            instance_id: string;
            approval_request_id: string;
            task_id: string;
            /** @enum {string} */
            status: "APPROVED" | "REJECTED" | "CANCELED";
            /** @enum {string} */
            outcome: "approved" | "rejected" | "canceled";
            source: components["schemas"]["WorkflowResultWebhookSourceDto"];
        };
        WorkflowResultWebhookDto: {
            /** @example mongodb:66a123... */
            id: string;
            /** @enum {string} */
            type: "APPROVAL_REQUEST_APPROVED" | "APPROVAL_REQUEST_REJECTED" | "APPROVAL_REQUEST_CANCELED";
            /** Format: date-time */
            occurred_at: string;
            data: components["schemas"]["WorkflowResultWebhookDataDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Templates_findAll: {
        parameters: {
            query?: {
                /** @description true면 관리 권한이 있어도 배포된 버전만 돌려준다. 신청 화면처럼 실제 실행될 버전의 입력 폼이 필요할 때 쓴다 */
                publishedOnly?: boolean;
                activeOnly?: boolean;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_execute: {
        parameters: {
            query?: never;
            header: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                "idempotency-key": string;
                /** @description 1~200자의 중복 실행 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartWorkflowDto"];
            };
        };
        responses: {
            /** @description 동기 실행이 제한 시간 안에 완료됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description 비동기 실행이 접수됨 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_start: {
        parameters: {
            query?: never;
            header: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                "idempotency-key": string;
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartWorkflowDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_findAll: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_result: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResultDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_terminate: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                /** @description 1~200자의 중복 처리 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminateInstanceResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 같은 Idempotency-Key가 다른 종료 요청에 사용됨 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_trace: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceEventDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_stream: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_getTasks: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_history: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: unknown;
                to?: string;
                from?: string;
                approver_channel?: "pxm_user" | "external_email";
                assignee?: unknown;
                instance_id?: unknown;
                workflow_id?: unknown;
                status?: unknown;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskPageDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_historyItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 결재 Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_completeTask: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                /** @description 중복 처리 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 결재 Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteApprovalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    InstanceTasks_history: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: unknown;
                status?: unknown;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskPageDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tools_list: {
        parameters: {
            query?: {
                /** @description 쉼표로 여러 값. 하나라도 맞으면 포함 */
                tags?: unknown;
                /** @description 쉼표로 여러 값 */
                side_effect?: unknown;
                naming?: "auto" | "qualified" | "plain";
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolListResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tools_invocation: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 완료 또는 업무 실패 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInvokeResponseDto"];
                };
            };
            /** @description 결재 대기 또는 진행 중 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInvokeResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tools_describe: {
        parameters: {
            query?: {
                group_id?: unknown;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolDefinitionDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tools_invoke: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                /** @description 1~200자의 중복 실행 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ToolInvokeDto"];
            };
        };
        responses: {
            /** @description 완료 또는 업무 실패 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInvokeResponseDto"];
                };
            };
            /** @description 결재 대기 또는 진행 중 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInvokeResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
}
