/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 가능한 워크플로우 목록 조회 */
        get: operations["Templates_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크플로우 상세 조회 */
        get: operations["Templates_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 워크플로우 실행
         * @description API Key 요청은 배포된 버전만 실행합니다.
         */
        post: operations["Templates_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 워크플로우 실행 (호환 별칭) */
        post: operations["Templates_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 접근 가능한 실행 목록 조회 */
        get: operations["Instances_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 상태 조회 */
        get: operations["Instances_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 결과 조회 */
        get: operations["Instances_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 Trace 조회 */
        get: operations["Instances_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 이벤트 스트림 구독 */
        get: operations["Instances_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 결재 대기 목록 조회 */
        get: operations["Tasks_getTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 이력 조회 */
        get: operations["Tasks_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 상세 조회 */
        get: operations["Tasks_historyItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결재 승인 또는 반려 */
        post: operations["Tasks_completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instanceId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 인스턴스의 결재 이력 조회 */
        get: operations["InstanceTasks_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    workflowResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PXM이 외부 시스템으로 전송하는 최종 결재 결과
         * @description 서명 입력은 `${X-PXM-Timestamp}.${raw_request_body}`이며 HMAC-SHA256으로 검증합니다. 동일 Idempotency-Key는 중복 처리하지 않습니다.
         *
         *     ```js
         *     const expected = 'v1=' + createHmac('sha256', secret)
         *       .update(`${timestamp}.${rawBody}`)
         *       .digest('hex');
         *     const valid = timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
         *     ```
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-PXM-Event-Id": string;
                    "X-PXM-Timestamp": string;
                    "X-PXM-Signature": string;
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowResultWebhookDto"];
                };
            };
            responses: {
                /** @description 처리 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 이미 처리한 이벤트 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        PublicApiErrorDto: {
            /** @example 403 */
            statusCode: number;
            /** @example Forbidden */
            error: string;
            /** @example MISSING_SCOPE */
            code: string;
            /** @example workflow:execute scope is required */
            message: string;
            details?: string[];
            /** @example workflow:execute */
            required_scope?: string;
            /** @example client-request-42 */
            request_id: string;
            /** Format: date-time */
            timestamp: string;
            /** @example /api/v1/templates/workflow-1/start */
            path: string;
        };
        WorkflowDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            group?: string;
            group_id?: Record<string, never> | null;
            tags: string[];
            version: number;
            /** @enum {string} */
            lifecycle_status: "DRAFT" | "PUBLISHED" | "DISABLED";
            nodes: {
                [key: string]: unknown;
            }[];
            edges: {
                [key: string]: unknown;
            }[];
        };
        StartWorkflowDto: {
            /**
             * @default async
             * @enum {string}
             */
            mode: "async" | "sync";
            sync_timeout_ms?: number;
            input?: {
                [key: string]: unknown;
            };
            /**
             * @example {
             *       "requestTitle": "구매 승인",
             *       "amount": 125000
             *     }
             */
            formData?: {
                [key: string]: unknown;
            };
            preset?: string;
            preset_id?: string;
            preset_alias?: string;
        };
        StartWorkflowResponseDto: {
            /** Format: uuid */
            instance_id: string;
            /** Format: uuid */
            template_id: string;
            template_name: string;
            /** @example CREATED */
            status: string;
            /** @enum {string} */
            mode: "async" | "sync";
            idempotent_replay: boolean;
            /** @example /api/v1/instances/instance-id/result */
            result_url: string;
            /** @example /api/v1/instances/instance-id/trace */
            trace_url: string;
            /** @example /api/v1/instances/instance-id/stream */
            stream_url: string;
        };
        InstanceDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            process_definition_id?: string;
            /** @example RUNNING */
            state: string;
            context?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        InstanceResultDto: {
            /** Format: uuid */
            instance_id: string;
            /** @example COMPLETED */
            status: string;
            result?: {
                [key: string]: unknown;
            } | null;
            result_path?: Record<string, never> | null;
            /** Format: date-time */
            completed_at?: Record<string, never> | null;
            /** Format: date-time */
            updated_at?: Record<string, never> | null;
        };
        TraceEventDto: {
            id: number;
            event_type?: string;
            node_id?: string;
            node_label?: string;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        ApprovalTaskDto: {
            task_id: string;
            instance_id: string;
            workflow_id?: Record<string, never> | null;
            workflow_name?: Record<string, never> | null;
            node_label?: Record<string, never> | null;
            /** @example OPEN */
            status: string;
            assignee: string;
            /** @example pxm_user */
            approver_channel: string;
            approval_channels?: string[];
            action?: Record<string, never> | null;
            comment?: Record<string, never> | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: Record<string, never> | null;
        };
        ApprovalTaskPageDto: {
            items: components["schemas"]["ApprovalTaskDto"][];
            next_cursor?: Record<string, never> | null;
        };
        CompleteApprovalDto: {
            /** @enum {string} */
            action: "approve" | "reject";
            comment?: string;
            result?: {
                [key: string]: unknown;
            };
        };
        WorkflowResultWebhookSourceDto: {
            /** @example acrapoint */
            provider: string;
            /** @example ACRA-2026-0042 */
            request_id: string;
            /** @example 1 */
            revision: number;
        };
        WorkflowResultWebhookDataDto: {
            instance_id: string;
            approval_request_id: string;
            task_id: string;
            /** @enum {string} */
            status: "APPROVED" | "REJECTED" | "CANCELED";
            /** @enum {string} */
            outcome: "approved" | "rejected" | "canceled";
            source: components["schemas"]["WorkflowResultWebhookSourceDto"];
        };
        WorkflowResultWebhookDto: {
            /** @example mongodb:66a123... */
            id: string;
            /** @enum {string} */
            type: "APPROVAL_REQUEST_APPROVED" | "APPROVAL_REQUEST_REJECTED" | "APPROVAL_REQUEST_CANCELED";
            /** Format: date-time */
            occurred_at: string;
            data: components["schemas"]["WorkflowResultWebhookDataDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Templates_findAll: {
        parameters: {
            query?: {
                activeOnly?: boolean;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_execute: {
        parameters: {
            query?: never;
            header: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                "idempotency-key": string;
                /** @description 1~200자의 중복 실행 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartWorkflowDto"];
            };
        };
        responses: {
            /** @description 동기 실행이 제한 시간 안에 완료됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description 비동기 실행이 접수됨 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Templates_start: {
        parameters: {
            query?: never;
            header: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                "idempotency-key": string;
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 워크플로우 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartWorkflowDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflowResponseDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_findAll: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_findOne: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_result: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResultDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_trace: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceEventDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Instances_stream: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_getTasks: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"][];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_history: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: unknown;
                to?: string;
                from?: string;
                approver_channel?: "pxm_user" | "external_email";
                assignee?: unknown;
                instance_id?: unknown;
                workflow_id?: unknown;
                status?: unknown;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskPageDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_historyItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 결재 Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    Tasks_completeTask: {
        parameters: {
            query?: never;
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
                /** @description 중복 처리 방지 키 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 결재 Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteApprovalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
    InstanceTasks_history: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: unknown;
                status?: unknown;
            };
            header?: {
                /** @description 호출자가 지정하는 요청 추적 ID. 생략하면 서버가 생성합니다. */
                "X-Request-ID"?: string;
            };
            path: {
                /** @description 인스턴스 ID */
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskPageDto"];
                };
            };
            /** @description API Key가 없거나 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 필요한 scope가 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 리소스가 없거나 접근 범위 밖임 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
            /** @description 내부 정보가 제거된 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApiErrorDto"];
                };
            };
        };
    };
}
